name: Post coverage comment

on:
  pull_request:
    types: [synchronize, opened, reopened, edited, ready_for_review]

jobs:
  test:
    name: Add coverage report comment
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Wait for coverage report
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          checks-name: 'Store coverage file'
          wait-interval: 10

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: tests.yml
          workflow_conclusion: success
          name: coverage
          if_no_artifact_found: warn

      - name: Post comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          COMMENT_TEMPLATE: '
            {% extends "base" %}
            {% block coverage_by_file %}
            <details>
            <summary>Full Coverage Report (click to unfold)</summary>
            {% for file_coverage in coverage.files.values() %}
            {{ file_coverage.path }}: {{ ((file_coverage.info.percent_covered * 100)|int) }}%<br>
            {% endfor %}
            </details>
            {{ super() }}
            {% endblock coverage_by_file %}
          '