name: Python tests

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["3.9"]
    environment: tests

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r lint_requirements.txt
          pip install -r tests_requirements.txt
          cd bin/resources/HTML
          python setup.py install

      - name: Check isort
        uses: jamescurtin/isort-action@master

      - name: Check flake8
        run: flake8 .

      - name: Check black
        uses: psf/black@stable

      - name: Test with pytest
        run: |
          export YANGCATALOG_CONFIG_PATH=$PWD/tests/resources/test.conf
          export PYTHONPATH=$PWD/bin:$PYTHONPATH
          export VIRTUAL_ENV=$PWD
          pytest --junitxml=pytest.xml --cov=. | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          title: Coverage Report
          pytest-coverage-path: pytest-coverage.txt
          junitxml-title: Coverage Summary
          junitxml-path: pytest.xml
          badge-title: Coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false